services:
  llama-cpp:
    image: ghcr.io/ggml-org/llama.cpp:server-cuda
    ports:
      - "${LLAMA_ARG_PORT}:${LLAMA_ARG_PORT}"
    volumes:
      - "./models:/models"
    healthcheck:
      test: >
        curl --fail http://localhost:8000/health || exit 1
      interval: 5m
      timeout: 5s
      retries: 5
      start_period: 30s
    pull_policy: always
    tty: true
    env_file:
      - path: .env
        required: true
      - path: .env.local
        required: false
    command: >
      --jinja
      --reasoning-format deepseek
    networks:
      - localgpt-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  open-webui:
    image: ghcr.io/open-webui/open-webui:v0.6.5
    ports:
      - "${CHAT_UI_PORT}:8080"
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - llama-cpp
    tty: true
    env_file:
      - path: .env
        required: true
      - path: .env.local
        required: false
    networks:
      - localgpt-network

volumes:
  open-webui:

networks:
  localgpt-network:
    driver: bridge
